In [1]:
import torch

# Is PyTorch Working

In [2]:
torch.version.__version__

'1.6.0'

In [3]:
a = torch.ones(3,3)

b = torch.ones(3,3)

a+b

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [4]:
torch.cuda.is_available()

True

# Pretrained models

In [5]:
from torchvision import models

In [6]:
dir(models)

['AlexNet',
 'DenseNet',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'Inception3',
 'InceptionOutputs',
 'MNASNet',
 'MobileNetV2',
 'ResNet',
 'ShuffleNetV2',
 'SqueezeNet',
 'VGG',
 '_GoogLeNetOutputs',
 '_InceptionOutputs',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_utils',
 'alexnet',
 'densenet',
 'densenet121',
 'densenet161',
 'densenet169',
 'densenet201',
 'detection',
 'googlenet',
 'inception',
 'inception_v3',
 'mnasnet',
 'mnasnet0_5',
 'mnasnet0_75',
 'mnasnet1_0',
 'mnasnet1_3',
 'mobilenet',
 'mobilenet_v2',
 'quantization',
 'resnet',
 'resnet101',
 'resnet152',
 'resnet18',
 'resnet34',
 'resnet50',
 'resnext101_32x8d',
 'resnext50_32x4d',
 'segmentation',
 'shufflenet_v2_x0_5',
 'shufflenet_v2_x1_0',
 'shufflenet_v2_x1_5',
 'shufflenet_v2_x2_0',
 'shufflenetv2',
 'squeezenet',
 'squeezenet1_0',
 'squeezenet1_1',
 'utils',
 'vgg',
 'vgg11',
 'vgg11_bn',
 'vgg13',
 'vgg13_bn',
 'vgg16',
 'vg

In [8]:
resnet = models.resnet101(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth" to C:\Users\jsevilla/.cache\torch\hub\checkpoints\resnet101-5d3b4d8f.pth


In [9]:
resnet

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

## Transforming inputs

In [20]:
from torchvision import transforms
from PIL import Image

img = Image.open('data/cj.jpg')

In [11]:
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225])
])

In [64]:
img.show()

In [24]:
img_t = preprocess(img)
batch_t = torch.unsqueeze(img_t, 0)

In [65]:
img_t.shape
batch_t.shape

torch.Size([1, 3, 224, 224])

### Inference on new data

In [27]:
resnet.eval()

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [28]:
out = resnet(batch_t)
out

tensor([[-3.0002e+00, -1.2094e+00, -9.1074e-01, -9.1238e-01, -3.4428e-01,
         -7.8070e-02, -2.0188e+00, -2.0053e+00, -1.9893e+00, -3.7101e+00,
         -3.6414e+00, -3.3108e+00, -3.5821e+00, -2.7040e+00, -3.1490e+00,
         -1.4843e+00, -5.3980e-01, -1.3450e+00,  5.7719e-02, -9.9254e-01,
         -2.4343e+00, -4.4803e+00, -2.7077e+00, -1.4509e+00, -2.7523e+00,
          2.1583e-01, -8.3079e-01, -1.6328e+00, -1.1386e+00,  1.4768e+00,
         -5.2788e-01, -2.9060e-01, -4.6578e-01,  6.8112e-01,  1.5003e+00,
          6.3653e-01,  1.3999e+00,  1.2462e+00,  7.4597e-01, -5.7849e-01,
         -1.5645e+00, -1.2104e+00, -1.9582e+00, -4.5018e-01, -9.6328e-01,
         -2.1105e-01, -9.0994e-01,  8.6247e-01, -9.0329e-01, -5.6737e-01,
         -4.6671e-02,  9.7632e-01, -7.9318e-01, -1.5508e+00,  5.6350e-01,
         -1.5430e+00, -1.3615e+00, -1.8426e+00, -2.9543e+00, -8.0211e-01,
         -3.9976e-01, -2.0039e-01, -2.4439e-01, -1.6130e+00, -1.0130e+00,
         -1.7363e+00, -5.7366e-01,  1.

In [29]:
with open('data/imagenet_classes.txt') as f:
    labels = [line.strip() for line in f.readlines()]

In [30]:
_, index = torch.max(out, 1)

In [35]:
percentage = torch.nn.functional.softmax(out, dim=1)[0]*100
labels[index[0]], percentage[index[0]].item()

('Boston bull, Boston terrier', 89.36041259765625)

In [37]:
_, indices = torch.sort(out, descending=True)
[(labels[idx], percentage[idx].item()) for idx in indices[0][:5]]

[('Boston bull, Boston terrier', 89.36041259765625),
 ('French bulldog', 6.074792861938477),
 ('doormat, welcome mat', 0.5948336720466614),
 ('toy terrier', 0.3977627158164978),
 ('Cardigan, Cardigan Welsh corgi', 0.2743774950504303)]

In [55]:
tensor = torch.Tensor(list(range(9)))

In [56]:
tensor.storage_offset()

0

In [57]:
b = tensor.view(3,3)

In [58]:
b

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [59]:
id(tensor.storage) == id(b.storage)

True

In [60]:
tensor.cos()

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])